version: '3'

services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: volun_near_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345password
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d


  spring-boot-app:
    build:
      context: .
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
