version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345password
      MYSQL_DATABASE: volun_near_app_db

  spring-boot-app:
    restart: on-failure
    build:
      context: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
