spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/volun_near_app_db?createDatabaseIfNotExist=true"
    username: "root"
    password: "12345password"
  jpa:
    open-in-view: false
#    hibernate:
#      ddl-auto: validate
    generate-ddl: true
server:
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
jwt:
  token:
    secret: "volun-near-app-2024"
    lifetime: 30m