INSERT INTO roles (name)
SELECT 'ROLE_VOLUNTEER' WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_VOLUNTEER'
);

INSERT INTO roles (name)
SELECT 'ROLE_ORGANISATION' WHERE NOT EXISTS (
    SELECT 1 FROM roles WHERE name = 'ROLE_ORGANISATION'
);